trigger:
- main
- master

variables:
  teamName: Roslyn-Project-System
  _DotNetArtifactsCategory: .NETCore
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedKey:
    PB_PublishBlobFeedUrl:
    _PublishUsingPipelines: false
    _DotNetPublishToBlobFeed: false
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedUrl: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    _DotNetPublishToBlobFeed: true
    _PublishUsingPipelines: true

phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    queue:
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        name: Hosted VS2017
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        name: DotNetCore-Windows
        demands:
        - agent.os -equals Windows_NT        
      parallel: 2
      matrix:
        ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
        Build_Release:
          _BuildConfig: Release
          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: none
            _SignType: test
          ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: blob
            _SignType: real

- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    agentOs: Linux_Source_Build
    queue:
      name: DotNetCore-Linux
      parallel: 2
      matrix:
        Build_Release:
          _BuildConfig: Release
          _PublishType: none
          _SignType: real
    variables:
      _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
    enableSourceBuild: true

- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: /eng/build.yml
    parameters:
      agentOs: Linux
      queue: 
        name: DotNetCore-Linux
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

  - template: /eng/build.yml
    parameters:
      agentOs: Darwin
      queue: 
        name: Hosted macOS
        parallel: 2
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/phases/publish-build-assets.yml
    parameters:
      publishUsingPipelines: true
      dependsOn:
        - Windows_NT
      queue:
        name: Hosted VS2017
