trigger:
- main
- master

variables:
  teamName: Roslyn-Project-System
  _DotNetArtifactsCategory: .NETCore
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedKey:
    PB_PublishBlobFeedUrl:
    _PublishUsingPipelines: false
    _DotNetPublishToBlobFeed: false
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedUrl: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    _DotNetPublishToBlobFeed: true
    _PublishUsingPipelines: true

jobs:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    pool:
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        name: Hosted VS2017
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        name: NetCoreInternal-Pool
        queue: BuildPool.Server.Amd64.VS2017
        demands:
        - agent.os -equals Windows_NT
    strategy:
      matrix:
        ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
        Build_Release:
          _BuildConfig: Release
          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: none
            _SignType: test
          ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: blob
            _SignType: real

- template: /eng/common/templates/job/source-build.yml
  parameters:
    platform:
      name: Managed
      container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343

- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: /eng/build.yml
    parameters:
      agentOs: Linux
      pool: 
        name: DotNetCore-Linux
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
      _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

  - template: /eng/build.yml
    parameters:
      agentOs: Darwin
      pool: 
        name: Hosted macOS
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/job/publish-build-assets.yml
    parameters:
      publishUsingPipelines: true
      dependsOn:
        - Windows_NT
        - Source_Build_Managed
      pool:
        name: Hosted VS2017
